In [1]:
## first we are gonna do is to perform one hot encoding representation for a specific word
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### example sentence to check one_hot_encoding
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
##now We need to define the size of the vacab and convert each word into vectors
voc_size=10000

In [4]:
### Performing one_hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
## for every word in the sentence we are implementing one_hot thats why we have passed 2 parameters inside one_hot, voc_size will decide for each word it will create a matrix of size 10000(voc_size) and it will put 1 on the position where the word is present.
## And by covering it by square brackets we are creating a list of these vectors.
one_hot_repr

[[9539, 6081, 5527, 2194],
 [9539, 6081, 5527, 1153],
 [9539, 8477, 5527, 9771],
 [8318, 5097, 1676, 7841, 7631],
 [8318, 5097, 1676, 7841, 8831],
 [963, 9539, 7400, 5527, 5768],
 [385, 8997, 4887, 7841]]

In [5]:
## we can see the above o/p it 
##[6226, 5621, 4994, 8235]
##  the , glass, of, milk,  at 6226 position the is present so we will find one inside this matrix, and same goes for every word.


## Now we will take all these words sentence by sentence and pass them to word embedding layers and then we will convert it into word embedding representation




In [6]:
### Word Embedding Representation  {Reffer notes from notebook}
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

## using pad_sequence we are making sixe of each vector same that will help training our model

[[   0    0    0    0 9539 6081 5527 2194]
 [   0    0    0    0 9539 6081 5527 1153]
 [   0    0    0    0 9539 8477 5527 9771]
 [   0    0    0 8318 5097 1676 7841 7631]
 [   0    0    0 8318 5097 1676 7841 8831]
 [   0    0    0  963 9539 7400 5527 5768]
 [   0    0    0    0  385 8997 4887 7841]]


In [9]:
## Feature representation
dim=10 ## Dimension of our word embedding model

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')  ## adam is optimizer and mse = loss function

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 70ms/step


array([[[-4.04323824e-02,  1.08019710e-02, -2.09774021e-02,
         -4.44298871e-02, -4.49669734e-02,  1.16877556e-02,
          1.77844651e-02, -3.17363515e-02, -3.46070416e-02,
          1.75794698e-02],
        [-4.04323824e-02,  1.08019710e-02, -2.09774021e-02,
         -4.44298871e-02, -4.49669734e-02,  1.16877556e-02,
          1.77844651e-02, -3.17363515e-02, -3.46070416e-02,
          1.75794698e-02],
        [-4.04323824e-02,  1.08019710e-02, -2.09774021e-02,
         -4.44298871e-02, -4.49669734e-02,  1.16877556e-02,
          1.77844651e-02, -3.17363515e-02, -3.46070416e-02,
          1.75794698e-02],
        [-4.04323824e-02,  1.08019710e-02, -2.09774021e-02,
         -4.44298871e-02, -4.49669734e-02,  1.16877556e-02,
          1.77844651e-02, -3.17363515e-02, -3.46070416e-02,
          1.75794698e-02],
        [ 1.56602003e-02, -2.31147539e-02,  1.70740150e-02,
         -3.15801725e-02, -3.08591127e-03,  3.72182988e-02,
         -2.44504809e-02, -4.59312685e-02, -2.705400